version: "3"
networks:
  my_network:
services:
  cliente:
    build: ./cliente
    container_name: cliente
    ports: 
      - 8088:80
    volumes:
      - "./cliente:/var/www/html"
    depends_on:
      - cartero
    networks:
      - my_network
  cartero:
    build: ./cartero
    container_name: cartero
    ports: 
      - 8081:80
    volumes:
      - "./cartero:/var/www/html"
    networks:
      - my_network